set_property SRC_FILE_INFO {cfile:D:/xilinx_project/zync7000_test/Open_Source_IoT/1_PlayGround/2_PMOD_LED_Control/2_PMOD_LED_Control.srcs/constrs_1/new/pmod_led.xdc rfile:../../../2_PMOD_LED_Control.srcs/constrs_1/new/pmod_led.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H15 [get_ports {gpio_rtl_tri_o[3]}]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15 [get_ports {gpio_rtl_tri_o[2]}]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W16 [get_ports {gpio_rtl_tri_o[1]}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V12 [get_ports {gpio_rtl_tri_o[0]}]
