set_property PACKAGE_PIN H15 [get_ports {gpio_rtl_tri_o[3]}]
set_property PACKAGE_PIN J15 [get_ports {gpio_rtl_tri_o[2]}]
set_property PACKAGE_PIN W16 [get_ports {gpio_rtl_tri_o[1]}]
set_property PACKAGE_PIN V12 [get_ports {gpio_rtl_tri_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_o[0]}]
